### ISSUE TITLE
Documentation: Broken Link

### ISSUE THREAD

**Issue by iamazeem** [biojava/biojava-spark#7]
Hi,

The following link for the [initial instructions](https://github.com/biojava/biojava-spark#some-initial-instructions-can-be-found-on-the-mmtf-spark-project) is broken:
https://github.com/rcsb/mmtf-spark

This seems to be the correct link:
https://github.com/sbl-sdsc/mmtf-spark

Regards!

**Comment by heuermh** [comment]
Fixed by pull request #8
